### ISSUE TITLE
Mob list?

### ISSUE THREAD

**Issue by Regularitee** [pisskop/PKs_Rebalancing#14]
Not really an issue, but a question:

I'm looking into the feasibility of creating a compatibility patch for PK's Re-balancing and a graphics pack. It would be useful and time-saving if I could find a consolidated master list of all the mobs added to the base game, rather than having to pluck them out of the code one at a time. Note that I'm looking for the mob IDs (e.g. mon_zombie_hulk) and not the common names (e.g. Zombie Hulk).

Does such a list exist? If it doesn't, no worries, I'll just have to make due doing things the old fashioned way.

**Comment by pisskop** [comment]
hang on I can drag out a list of all new monsters ids and the ids of any coregame monster whose color scheme I alter.

tomorrow?

**Comment by pisskop** [comment]
I lied.  below is the list, I warn you it is long

https://www.dropbox.com/s/2c8qaiaygpwh8bg/monster_dump.txt?dl=0
^^link to .txt file

`"mon_ant_scrib" - forager ant
"mon_ant_terminal" - giant ant
"mon_ant_soldier_terminal" - soldier ant
"mon_ant_soldier_pk_weak" - jack ant
"mon_ant_soldier_pk" - jack ant
"mon_ant_queen_firebug" - queen ant
"mon_ant_queen_young" - young queen ant
"mon_ant_male" - male ant

"mon_imp" - imp
"mon_imp_black" - imp (black)
"mon_pinky" - demon
"mon_lostsoul" - lost soul
"mon_revenant" - revenant
"mon_hell_knight" - hell knight
"mon_hell_baron" - hell baron
"mon_mancubus" - mancubus
"mon_cacodemon" - cacodemon
"mon_mechaspider" - arachnotron
"mon_cyberdemon" - cyberdemon
"mon_doom_churl" - churl (human warrior)
"mon_doom_slave" - slave (human slave)
"mon_doom_cur" - zombie slave (ala what the pc makes)
"mon_lostsoul_mount" - lost soul
"mon_doom_sacrifice" - mutilated zombie (ala blood sacrifice)
"mon_soulcube" - soulcube (doom 3)
"mon_doom_archvile" - vile
"mon_doom_archvile_2" - vile
"mon_doom_archvile_3" - vile
"mon_doom_archvile_4" - vile
"mon_doom_archvile_5" - vile
"mon_doom_archdemon" - archdemon (doom 2)

"mon_doom_archvile_queen" - archvile (boss archvile)
"mon_imp_revive" - scarred imp
"mon_pinky_revive" - scarred demon
"mon_hell_knight_revive" - battered hell knight
"mon_cacodemon_revive" - abhorrent cacodemon
"mon_doom_churl_revive" - enslaved churl

"mon_fungus_boil" - fungal boil
"mon_fougar" - fungal cougar
"mon_feer" - deer (exploding deer)
"mon_foose" - foose (fungal moose)
"mon_folf" - wolf (fungal wolf)
"mon_fant" - fant (fungal ant v2)
"mon_fungaloid_pk" - fungal tender
"mon_fardigrade" - infected tardigrade (fungal waterbug)
"mon_furvivor" - fungal survivor (heavily infected survivor)
"mon_furvivor_glock" - infected survivor
"mon_furvivor_shotgun" - infected survivor
"mon_furvivor_deagle" - infected survivor
"mon_furvivor_smg" - infected survivor
"mon_furvivor_pk" - infected survivor (melee)
"mon_marloss_man" - marloss man
"mon_finebeast" - fungal vinebeast
"mon_fionaea" - fungal dionaea
"mon_finecraft" - fungal brood (fungal minecraft creeper)
"mon_zombie_electric_fungal" - fungal shocker
"mon_fungus_pig" - squig (warhammer)

"mon_maggot" - giant maggot
"mon_caterpillar" - giant caterpillar
"mon_pupae" - pupal sac (think pokemon-metapod)
"mon_pupae_pk" - pupal sac (think pokemon-metapod)
"mon_butterfly" - giant butterfly
"mon_moth" - giant moth
"mon_tardigrade" - tardigrade (waterbug)
"mon_spider_wolf_giant_pk" - huge wolf spider
"mon_spider_web_queen" - large egg sac (boss enemy)
"mon_trapdoor_egg" - egg sac
"mon_trapdoor_queen" - large egg sac (boss)
"mon_spider_trapdoor_giant_s" - giant immature trapdoor spider
"mon_spider_trapdoor_giant_guardian" - alpha giant trapdoor spider
"mon_spider_trapdoor_giant_pk" - giant trapdoor spider (v2 of base)
"mon_spider_web_alpha" - giant web spider (brutal poison)
"mon_spider_web_omega" - giant web spider (longlasting poison)
"mon_spider_web_mu" - giant web spider (fungus killer)
"mon_spider_jumping_giant_acid" - medusa spider
"mon_bee_scout" - giant bee (faster, weaker)
"mon_bee_soldier" - giant bee (slower stronger)
"mon_bee_queen" - giant queen bee (boss)
"mon_bee_king" - giant royal bee
"mon_bee_larvae" - bee larvae
"mon_wasp_queen" - queen wasp (boss)
"mon_wasp_larvae" - larval wasp

"mon_hallu_mannequin" - mannequin (hallucination)
"mon_bear_pk" - bear (strong)
"mon_bear_weak" - bear
"mon_cougar_pk" - cougar (strong)
"mon_cougar_weak" - cougar
"mon_dog_large" - large dog
"mon_moose_pk" - moose (strong)
"mon_moose_weak" - moose
"mon_skunk" - skunk
"mon_goat" - goat
"mon_gator" - sewer gator
"mon_robin" - robin
"mon_bjay" - blue jay
"mon_pidgeon" - pidgeon
"mon_bear_mega" - elephant bear
"mon_bear_mega_mating" - elephant bear (in heat/musk)
"mon_bear_mega_kid" - juvenille elephant bear
"mon_bear_mega_baby" - elephant bear cub
"mon_coyote_small" - dwarf coyote
"mon_pig_saber" - sabertooth pig
"mon_mole_large" - large mole

"mon_sludge_crawler_queen" - sludge crawler (boss)
"mon_jabberwock_pk" - jabberwock (v2)
"mon_bat_vampire" - vampire bat
"mon_coyote_wolf_zerg" - scythed coyote

"mon_cyborg_guard" - guard cyborg
"mon_cyborg_cop" - robotic cop
"mon_manhack_missile" - revenant rocket
"mon_manhack_fire" - firebomb hack
"mon_turret_shockcannon" - shockcannon
"mon_robot_drone" - helidrone

"mon_creeper_hub" - creeper hub (palette swap-> broken sprite)
"mon_biollante_pk" - glowing biollante
"mon_creeper_vine_terminal" - creeping grass (dying)
"mon_creeper_vine_pk" - creeping vine
"mon_creeper_vine_terminal_pk" - creeping vine (dying)
"mon_creeper_root" - slithering root (burrows)
"mon_vinebeast_terminal" - vinebeast (v2)
"mon_vinebeast_pk" - tangala (v2 -pokemonish)
"mon_triffid_pk" - triffid (v2)
"mon_treent" - blue aurora
"mon_treent_green" - treunt
"mon_dionaea_sprout" - dionaea sprout
"mon_dionaea" - dionaea (little shop of horrors)
"mon_minecraft" - hissing brood (minecraft creeper)
"mon_minecraft_charged" - charged hissing brood (minecraft creeper)

"mon_zolf_shady" - dark howler
"mon_horse_zombie" - zombie horse
"mon_zombie_dog_pk" - zombie chaser (dog v2)
"mon_dog_skeleton_pk" - hell hound (skele dog v2 smoker)
"mon_dog_zombie_cop_pk" - zombie hunting dog (rubber z9)
"mon_zombie_scorched_pk" - scorched zombie (2nd stage burn)
"mon_zombie_scorched_shocker" - scorched zombie
"mon_zombie_fiend_pk" - fiend (2nd stage burn)
"mon_zombie_fiend_shocker" - fiend (shocker brute burned)
"mon_zombie_crawler_scorched" - gutted zombie (3rd stage burn)
"mon_skeleton_scorched" - gutted zombie (not meant to be alive, but a prop for the corpse item, too burnt to live)
"mon_zombie_scorched_necro" - zombie abomination
"mon_zombie_scorched_master" - zombie abomination
"mon_zombie_child_scorched_2" - burned child zombie (burn stage 2)
"mon_horse_zombie_scorched" - hooved horror (burnt large-mammal zed)
"mon_zolf_scorched" - torrid beast (stage 1 'medium' animal burnt)
"mon_zanimal_scorched" - putrid pile (stage 2 medani burnt)
"mon_zanimal_skeleton" - putrified pile (stage 3 medani burnt)
"mon_zanimal_skeleton_dead" - putrified pile (stage 4 - not meant to be alive but serves to prompt the proper nonreviving corpse item)
"mon_zombie_bear_mega" - zombie megabear

"mon_zombie_runner_pk" - feral runner
"mon_zombie_cripple" - maimed zombie
"mon_zombie_blind" - blind zombie
"mon_zombie_blind_pk" - unseeing zombie (threat to Early Game PCs)
"mon_zombie_2" - zombie
"mon_zombie_3" - zombie
"mon_zombie_pk" - hungry zombie
"mon_zombie_child_2" - zombie child
"mon_zombie_child_3" - zombie child
"mon_zombie_hollow_pk" - zombie nadir
"mon_zombie_fat_2" - fat zombie
"mon_zombie_fat_3" - fat zombie
"mon_beekeeper_pk" - scabby zombie (v2 scarred zombie)
"mon_zombie_child_pk" - zombie scrapper (v2 child zombie)
"mon_zombie_child_reaver" - zombie reaver (v3 child zombie)
"mon_zombie_tough_2" - tough zombie
"mon_zombie_tough_3" - tough zombie
"mon_zombie_electric_pk" - sparker zombie (v2 shocker)
"mon_zombie_shady_pk" - shadowed zombie (v2 shady)
"mon_zombie_shady_ghost" - ethereal zombie (v3 shady, 'ghostly')
"mon_zombie_master_pk" - zombie master (v2)
"mon_zombie_necro_pk" - zombie necromancer (v2)
"mon_zombie_lord" - zombie lord (necro/master combined)
"mon_zombie_swimmer_pk" - swimmer zombie
"mon_zombie_scales" - encrusted zombie (armored swimmer)
"mon_zombie_rot_pk" - rotting zombie
"mon_skeleton_pk" - zombie mangler (skele v2)
"mon_skeleton_husk" - zombie husk (skele v3)
"mon_zombie_crawler_pk_weak" - shambling zombie (crawling sludge zombie)
"mon_zombie_crawler_pk" - shambler (late-game threat crawling sludge zombie)
"mon_zombie_hulk_pk" - zombie tank (hulk v2)
"mon_boomer_huge_pk" - huge boomer (glow in dark boomer)
"mon_zombie_gasbag_pk" - putrid zombie (majiin boo sillyputty monster)
"mon_zombie_radbag" - smoldering zombie (very radioactive zombie)
"mon_zombie_smoker_pk" - zombie incus (smoker v2)
`

**Comment by Regularitee** [comment]
That's... actually not too bad. I thought it was a lot longer, but maybe that was just because I was looking at the code directly, which has a far longer number of lines of text. Nice. And thanks.

**Comment by pisskop** [comment]
Ill keep a list in .txt form in the mod
