### ISSUE TITLE
Missing Walls?

### ISSUE THREAD

**Issue by Regularitee** [pisskop/PKs_Rebalancing#15]
Since installing PKR, I've twice encountered buildings that, rather than being made of regular walls, were made of smoothed stone. The layout is identical to their regular variants, except for one issue: these smoothed-stone variants have no internal walls, which essentially means the entire building will be one giant room. The internal doors still appear in their expected places, just not the walls. 

I've encountered this issue with a museum and pizza parlour, but there could be more.

**Comment by ZenZen2** [comment]
i noticed that with museum too

**Comment by pisskop** [comment]
Yes.  Ill have it fixed up this weekend, hopefully.

**Comment by pisskop** [comment]
this is -should be- fixed
