### ISSUE TITLE
Bleeding bug

### ISSUE THREAD

**Issue by ZenZen2** [pisskop/PKs_Rebalancing#20]
Hello Pisskop,
the Forum is down, thats why i report in here. Bleeding causes a Debug and i was told it must be caused by your mod. Please look here for the whole report and answer.
https://github.com/CleverRaven/Cataclysm-DDA/issues/20555#issuecomment-287150424

**Comment by pisskop** [comment]
update your mod; i removed it due to it being too inflexible.

thanks for reporting the bug.  ive seen sometimes bugs happen where i cannot see them.  for instance on different OSs or when compiled by differing programs

**Comment by ZenZen2** [comment]
Thanks a lot :)
do i have to start a new game?

**Comment by pisskop** [comment]
Not for the fix.
