### ISSUE TITLE
mon_gator problem

### ISSUE THREAD

**Issue by ZenZen2** [pisskop/PKs_Rebalancing#21]
Hello Pisskop,
after your new patch, the game complains with 3 different debugs about mon_gator.
It happens on loading a save game but also on starting a new game.

cata version 6328

**Comment by ZenZen2** [comment]
with new patch i mean the 3.1.1 release.

**Comment by pisskop** [comment]
>.>
<.<

its been fixed, i didnt release it ...


https://github.com/pisskop/PKs_Rebalancing/releases/tag/3.1.1b


try this.

gator fix, sky vortex, stemcells
