### ISSUE TITLE
Plant harvesting tools missing.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [pisskop/PKs_Rebalancing#22]
There's a shift-a hoe for fast soil tilling, but there's no shift-a tool for fast plant harvesting. There's the scythe in game, but has no option except being a weapon.

Would be nice to have a tool for fast harvesting and not be forced to use vehicles in that regard.

**Comment by pisskop** [comment]
Unfortunately this is more of an issue for the core game.

I could look into it, but it sounds like a use-action, which is firmly c++ material.  At least for defining the actual actions.
