### ISSUE TITLE
Doom lab, The vault(necropoli), shipwreck and possibly some other overmap locations do not spawn

### ISSUE THREAD

**Issue by Neversalimus** [pisskop/PKs_Rebalancing#23]
Doom lab, The vault(necropoli), shipwreck and possibly some other overmap locations do not spawn, i'm using the newest to that moment experimental 6421, with mod off The Vault and necropolis spawn the same goes for shipwreck, with mod on it doesn't spawn (also some mod locations do not spawn too like doom lab and possibly wasp hives). Tried with only core mod and rebalance on, so it is not conflict with mods.

**Comment by pisskop** [comment]
I consider this fixed to an acceptable level.

Feel free to reopen this though if not.
