### ISSUE TITLE
Apis won't spawn with mod on

### ISSUE THREAD

**Issue by MagicalCube** [pisskop/PKs_Rebalancing#26]
its not a big problem because you can still debug spawn them albeit with a normal human name instead of apis as a name

my guess is that it has something to do with scabby zombies maybe changed map for hive. desu?

**Comment by pisskop** [comment]
Apis is the bee mutant?

Yes. I mod the center of the hive.  Ill look to see if I cant readd her.

**Comment by pisskop** [comment]
About this ... ...  hang on

**Comment by pisskop** [comment]
fixed in newest update.

**Comment by MagicalCube** [comment]
thank you :) I can rest happily now knowing that monstergirl meat is back on the menu 👍
