### ISSUE TITLE
CTD When Loading Map.

### ISSUE THREAD

**Issue by ghost** [pisskop/PKs_Rebalancing#27]
When using the latest experimental version, creating the world from the main menu produces no errors. However, when I go to start a game, I get a bunch of debug message, a failed assertion popup, and then the game crashes.

Heres the content of the assertion message, reproduced as best I could because I couldn't copy text out of it:   
Assertion Failed!

Program: C:\Users\Me\Doccuments\CDDA\cataclysm-tiles.exe
File: src/overmap.cpp, line 510

Expression: directional_peers.size() == om_direction::size

My debug log is attached. I'm using the default mods, and this mod, plus its dependency.
[debug.txt](https://github.com/pisskop/PKs_Rebalancing/files/1147240/debug.txt)

**Comment by ampnaman** [comment]
Seconding this, huge map crash on build 6690,

![crash](https://user-images.githubusercontent.com/30443081/29468422-b9e82acc-8476-11e7-8478-1dd384becc35.png)

**Comment by pisskop** [comment]
https://github.com/pisskop/PKs_Rebalancing/tree/5.3.6
done.
