### ISSUE TITLE
Cant create new Custom Character (reproducible)

### ISSUE THREAD

**Issue by drayath** [pisskop/PKs_Rebalancing#29]
Cant create new custom character.
Can successfully create custom character without pkmod.

Repo:
From launcher
Install latest cdda (0.C-23932-g9ab5c97)
Install latest pkmod (5.4.9)
Create new world with cdda core and pkmod only ("dda", "PK_REBALANCE")
Create new Custom character
While at step "Loading Content (PK_REBALANCE)" get the following error:
----
Error: item group already defined with different type
main_menu::new_character_tab() - main_menu.cpp:615
----
Continue past error returns back too main menu.
No debug log in for on what item group clashed.

**Comment by lehofin** [comment]
It seems this commit causes that: https://github.com/CleverRaven/Cataclysm-DDA/commit/3efc6374b9723e0c798be5bb0d9d65c2114b40d3
The names of vending machine item groups were changed from "vending_food" to "vending_food_items" and "vending_drink" to "vending_drink_items".
There's apparently only one instance of the "vending_food" group in this mod: line 1080 in spawns/pk_itemlist_edit.json

**Comment by lordlordsavage** [comment]
Having the exact same issue. Was just about to post about it.
![pk rebalancing issue](https://user-images.githubusercontent.com/31820162/30513045-cdc67886-9aca-11e7-9206-167a80665ace.png)

**Comment by drayath** [comment]
Looks like lehofin is correct

Tested Fix:
In spawns/pk_itemlist_edit.json:1080 replace "vending_food" with "vending_food_items",

**Comment by pisskop** [comment]
https://github.com/pisskop/PKs_Rebalancing/releases/tag/5.5.0

Here we go.  Yes, they tried to fix vending machine spawns and did so by making the vending_food/drink lists collections of items instead of items.
