### ISSUE TITLE
Use a different unique ident value in modinfo.json

### ISSUE THREAD

**Issue by remyroy** [pisskop/PKs_Rebalancing#30]
If you use a different ident value in your modinfo.json file, the CDDA launcher would keep both your mod in the base game and the custom mod when updating. This could be a temporary workaround for people that are updating with the launcher and losing your latest version of PK's Rebalancing because it gets overwritten by the one coming from the base game.

If you go ahead with this suggestion, it would probably be a good idea to give it a slightly different name to so people can see which one they are selecting in game. Maybe like *Experimental PK's Rebalancing* or something else.

This is a very small issue that could help many people. I might try to use a better solution with the launcher but there is no obvious and easy one I found so far.

**Comment by pisskop** [comment]
I should.  Id rather they take out the old one.

**Comment by pisskop** [comment]
okay
