### ISSUE TITLE
Weighted list 'default_groundcover' required for 'default'

### ISSUE THREAD

**Issue by WhatTheFox** [pisskop/PKs_Rebalancing#31]
```
"house_basement_chance": 6, 	"//": "one_in(n) houses with basements",
"default_oter": "field", 	"//": "default oter_id (anything that isn't a house/road/etc) some become forests",
"default_groundcover": {
	               ^
				"//": "biome settings for generic 'grass_or_dirt' (which is reproduced below",
"primarg": "t_grass", 		"//": "default ter_id on ground",
"ratio": 4, 			"//": "one_in(n) chance that it becomes..
 
FUNCTION : bool main_menu::load_character_tab()
FILE : src/main_menu.cpp
LINE : 841
```

Since updating Cataclysm DDA to the #6872 build (persists on #6873), I've been getting this error on either an existing character and a newly created character.

**Comment by lordlordsavage** [comment]
Having a similiar issue but the line is 615
![debug](https://user-images.githubusercontent.com/31820162/30566182-f8c8abce-9c98-11e7-8d19-250baab14b69.png)
Started at Build 6783

**Comment by WhatTheFox** [comment]
The error is in fact fixed in the current latest release. This issue can be closed.
