### ISSUE TITLE
Prison was moved to json

### ISSUE THREAD

**Issue by ZhilkinSerg** [pisskop/PKs_Rebalancing#32]
https://github.com/CleverRaven/Cataclysm-DDA/pull/21211 was merged recently, so `prison_6` in `\pk_overmap_terrain.json` and `prison_5` in `\locations\override\prison_entrance.json` should be probably renamed in the mod.

![default](https://user-images.githubusercontent.com/16213433/30828043-e8eb92aa-a244-11e7-916b-5cf2fe85dff2.png)

**Comment by pisskop** [comment]
aye, thank you.   Its in the new version.
