### ISSUE TITLE
Due to the changes how braziers work 

### ISSUE THREAD

**Issue by zakhad** [pisskop/PKs_Rebalancing#33]
These tags inside standing_stones.json and cavepit.json are no longer considered traps but furniture

      "traps": {
        "#": "tr_brazier"
      },

should be changed to

      "furniture": {
        "#": "f_brazier"
      },

or added into the furniture tag

*I simply deleted it as i don't know how to mod properly but it's been suggested in the discord for cdda that it should be changed to the furniture tag, and traps removed"

**Comment by pisskop** [comment]
This should be fixxed now.
