### ISSUE TITLE
[Build 6875] Issue "park_radius"

### ISSUE THREAD

**Issue by TheMrBakit** [pisskop/PKs_Rebalancing#34]
#Hello @pisskop,  
I receive an error upon loading week old game.
Here a a screenshot of the error ;
https://puu.sh/y39Zv/f01e054711.png

![f01e054711 1](https://user-images.githubusercontent.com/18709806/31846187-21871a90-b5d6-11e7-8464-e0537fe90ff3.png)
PS :The game won't load (back to the main menu)

**Comment by pisskop** [comment]
Fixxed for you in 5.5.9

**Comment by TheMrBakit** [comment]
Thanks @pisskop
