### ISSUE TITLE
Hotfix patch for 5.6.4c

### ISSUE THREAD

**Issue by ZhilkinSerg** [pisskop/PKs_Rebalancing#39]
## Description

Contains changes from #36, #37 and #38:

## Download links:

[2018-01-05_HotfixPatch_For_PKs_Rebalancing-5.6.4c.zip](https://github.com/pisskop/PKs_Rebalancing/files/1606790/2018-01-05_HotfixPatch_For_PKs_Rebalancing-5.6.4c.zip)

**Comment by baraba3** [comment]
Tnx man.

**Comment by ZenZen2** [comment]
Thanks for the Hotfix.
Did pisskop stop with this mod? Why was his Forum Thread closed?
I hope someone is able to keep this compatible for the future cataclysm versions.

**Comment by ZhilkinSerg** [comment]
He is on vacation probably.

**Comment by pisskop** [comment]
thanks for this.
