### ISSUE TITLE
Bees,wasps and mosquitoes are too deadlly

### ISSUE THREAD

**Issue by baraba3** [pisskop/PKs_Rebalancing#40]
Dont know is it a feature but in last several game i died to same reason-brief encounters with mosquitoes and bees which i killed but after that painkiller count started raising  and i died from breathing stopping.i was not stabbed that many times- not sureas as i was udner bone armor and i got onyl poisoning status. I have never had this problem before.

All of my characters were battle hardened survivors which dealt with far greater threats.

**Comment by holioo** [comment]
I agree that they are too strong. What's worse is that after getting stung you start to rapidly dehydrate and starve. Even if you survive the next night or two by constantly drinking water from a well, you will still be left with a near 50% speed penalty from the "near-starving" status. 

A few reasons why this is so frustrating is that for one, all the creatures that posses this trait are far faster than you and have very high dodge skills, meaning that they can potentially sting/stab you many times in a few turns. Another reason is that the only way to counter painkiller build up, to my knowledge, is the blood filter cbm, which itself is not always gaurenteed to be found. 

Of course you could just avoid wasps, beeshives, and swamps entirely, barring you from certain areas of the game. However, in that case the feature (if it is a feature; if it's simply an oversight of some sort than feel free to ignore most of this post) would only serve to remove content from the game, not add.

**Comment by baraba3** [comment]
in last few games effect dotn seem to be so noticeable as i survived several time being stabbed although only once so i dotn know if it changed but i avoid insects like plague anyway.

itnerstign thing is thatoenb time my npc got stabbed and he had problem with breating stopping but survived probably tnx to not beign playter.he on other hand drank i think 30 l of water andlot of fried dandelinbgs andbread to satisfy hunger thrist after.

**Comment by pisskop** [comment]
The breathing is due to high pkiller.

gonna nerf it a bit.

**Comment by pisskop** [comment]
Let me know if this is still a huge problem still.

Should be _possible_ to die by pkiller, should not be inevitable.
