### ISSUE TITLE
Tough zombie, monster_mon_ant and monster_mon_ant_larvae have both into and into_group defined : Bug

### ISSUE THREAD

**Issue by SilearFlare** [pisskop/PKs_Rebalancing#41]
As seen in https://github.com/CleverRaven/Cataclysm-DDA/issues/23034
oh yeah and @pisskop 
getcher ass here

**Comment by pisskop** [comment]
lol.

Its caused by the json being edited to add in new evos for ants.  Acid ants sound fun, tbh.
