### ISSUE TITLE
Typo in fungus.json

### ISSUE THREAD

**Issue by ZenZen2** [pisskop/PKs_Rebalancing#44]
Noticed it by getting instant killed by a Squig after one bite into full hp torso with leather armour protection. Looked into json's to check what the problem was.
The Typo is here:
```"min_mul": 85,```
```85``` need to be changed to ```0.85```
Looks like the typo was copy&pasted also to:
mon_furvivor
mon_furvivor_glock
mon_furvivor_shotgun
mon_furvivor_deagle
mon_furvivor_smg
mon_furvivor_pk
mon_fionaea
and mon_fungus_pig to make the list Full.

There is a small chance that this is intended, but that realy doesnt make sense to me. I am going to post it also on the forum because i am not sure if this github is used.

**Comment by pisskop** [comment]
thanks for reporting!
